### ISSUE TITLE
two sum algorithm in java

### ISSUE THREAD

**Issue by Souguiroumaima7** [Vanshikapandey30/Hacktoberfest2024#280]
class Solution {
    public int[] twoSum(int[] nums, int target) {

        Map<Integer, Integer> map = new HashMap<>();
        
        
        for (int i = 0; i < nums.length; i++) {
            map.put(nums[i], i);
            
            
        }
        for (int i = 0; i < nums.length; i++) {
            
            int complement = target - nums[i];
            
            if (map.containsKey(complement) && map.get(complement) != i) {
                
                
                return new int[] { i, map.get(complement) };
            }
        }
        
        // In case there is no solution, we'll just return null
        return null;
    }
}

**Comment by shivam-1810** [comment]
@Souguiroumaima7 What has to be actually done in this, if it has to be converted so as to make compatible with int array input, 
@Vanshikapandey30  please assign me this issue under hactoberfest, else explain me the issue in detail please..!

**Comment by Souguiroumaima7** [comment]
To convert input into a compatible integer array, first, parse the input string by splitting it into individual elements. Then, convert each element to an integer while handling potential errors for non-numeric values. Finally, return the resulting integer array for further use in the application.

def convert_input_to_int_array(input_string):
    try:
        input_array = input_string.split(", ")
        int_array = [int(num) for num in input_array]
        return int_array
    except ValueError:
        print("Error: Non-numeric value found in input.")
        return None

# Example usage:
input_string = "1, 2, 3, 4"
result = convert_input_to_int_array(input_string)
if result is not None:
    print("Converted integer array:", result)
